# Generated by Django 5.2.17 on 2026-08-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='provider_profile_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
