# Generated by Django 5.2.17 on 2026-09-06 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_membership_permissions_workspace_soft_budget_credits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'OWNER'), _negated=True), name='org_membership_owner_is_not_assignable'),
        ),
    ]
