# Generated by Django 5.2.17 on 2026-09-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_owner_not_assignable'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='addon_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
