# Generated by Django 5.2.17 on 2026-09-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_invitation_and_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_BILLING', 'Awaiting billing confirmation'), ('OVER_LIMIT', 'Over the plan limit')], default='ACTIVE', max_length=16),
        ),
    ]
