# Generated by Django 5.2.17 on 2026-09-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_multi_currency_pricing'),
        ('workspaces', '0008_workspace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='billing.currency'),
        ),
    ]
