# Generated by Django 5.2.17 on 2026-09-08 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0003_review_links'),
        ('workspaces', '0014_seed_chains_and_grandfather'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='guest_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to='collaboration.reviewlink'),
        ),
    ]
