# Generated by Django 5.2.17 on 2026-09-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_approvalaction_guest_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='required_permission',
            field=models.CharField(blank=True, choices=[('view', 'View content'), ('comment', 'Comment internally'), ('edit', 'Create and edit content'), ('approve', 'Approve content'), ('publish', 'Schedule and publish'), ('analyze', 'Read analytics'), ('admin', 'Administer the workspace')], max_length=16),
        ),
    ]
