# Generated by Django 5.2.17 on 2026-09-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0016_approval_action_required_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="market",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
