# Generated by Django 5.2.16 on 2026-08-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Immutable after creation (D13).', unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('price_monthly_cents', models.IntegerField(default=0)),
                ('price_annual_cents', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=64)),
                ('stripe_price_id_annual', models.CharField(blank=True, max_length=64)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('monthly_ai_credits', models.IntegerField(default=0)),
                ('included_videos', models.IntegerField(default=0)),
                ('max_social_accounts', models.IntegerField(default=1)),
                ('max_autopublish_posts', models.IntegerField(default=0)),
                ('max_scheduled_posts', models.IntegerField(default=0)),
                ('scheduling_horizon_days', models.IntegerField(default=7)),
                ('max_workspace_members', models.IntegerField(default=1)),
                ('max_products', models.IntegerField(default=1)),
                ('trial_days', models.IntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
