# Generated by Django 5.2.16 on 2026-08-04 19:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Signed. Zero is legitimate: unlimited plans still record usage.')),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('MONTHLY_GRANT', 'Monthly grant'), ('GENERATION', 'Generation'), ('REFUND', 'Refund'), ('MANUAL_ADJUST', 'Manual adjustment'), ('PURCHASE', 'Purchase'), ('TRIAL_GRANT', 'Trial grant')], max_length=16)),
                ('actor', models.ForeignKey(blank=True, help_text='Set for MANUAL_ADJUST so an operator action is attributable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_adjustments', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='billing.creditledger')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='billing_cre_workspa_d9f745_idx'), models.Index(fields=['workspace', 'reason'], name='billing_cre_workspa_299559_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELED', 'Canceled'), ('INCOMPLETE', 'Incomplete'), ('UNPAID', 'Unpaid')], default='INCOMPLETE', max_length=16)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('stripe_subscription_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='billing_sub_workspa_dfdb44_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Signed. Zero is legitimate: unlimited plans still record usage.')),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('MONTHLY_GRANT', 'Monthly grant'), ('GENERATION', 'Generation'), ('REFUND', 'Refund'), ('PURCHASE', 'Purchase'), ('MANUAL_ADJUST', 'Manual adjustment')], max_length=16)),
                ('unit_cost_cents', models.IntegerField(default=0, help_text='COGS at the time of the entry; overage is billed at cost + $2 (D16).')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_adjustments', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='billing.videoledger')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='billing_vid_workspa_b53933_idx')],
            },
        ),
    ]
