# Generated by Django 5.2.17 on 2026-08-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_ledger_append_only_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Immutable after creation, as for Plan (D13).', unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('CREDITS', 'Credits'), ('VIDEO', 'Video units')], max_length=8)),
                ('units', models.IntegerField(help_text='Credits, or video units, granted on payment.')),
                ('price_cents', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='videoledger',
            name='unit_cost_cents',
            field=models.IntegerField(default=0, help_text='Per-unit money for this entry: COGS on a generation, price paid on a purchase. Overage is sold at cost + $2 (D16).'),
        ),
    ]
