# Generated by Django 5.2.17 on 2026-08-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('billing', '0004_pack_alter_videoledger_unit_cost_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditledger',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger_entries', to='ai.generation'),
        ),
        migrations.AddField(
            model_name='videoledger',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_ledger_entries', to='ai.generation'),
        ),
    ]
