# Generated by Django 5.2.17 on 2026-08-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('billing', '0005_creditledger_generation_videoledger_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='credit_ledger_entries', to='ai.generation'),
        ),
        migrations.AlterField(
            model_name='videoledger',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='video_ledger_entries', to='ai.generation'),
        ),
    ]
