# Generated by Django 5.2.17 on 2026-09-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_creditledger_generation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='TRIALING', max_length=16)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_item_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['addon_key'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='comment_capture_interval_minutes',
            field=models.IntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='plan',
            name='counts_docs_against_quota',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_campaigns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_labels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_workspaces',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_per_workspace_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='reaction_detail',
            field=models.CharField(choices=[('TOTAL', 'Total count only'), ('PER_TYPE', 'Per-reaction-type breakdown'), ('REACTORS', 'Per-type plus reactor identities')], default='TOTAL', max_length=16),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_post_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='version_history_days',
            field=models.IntegerField(default=0),
        ),
    ]
