# Generated by Django 5.2.17 on 2026-09-06 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_featureflag_organizationaddon_and_more'),
        ('workspaces', '0004_membership_permissions_workspace_soft_budget_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='workspaces.organization'),
        ),
        migrations.AddField(
            model_name='organizationaddon',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='workspaces.organization'),
        ),
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('key',), name='unique_global_feature_flag'),
        ),
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'key'), name='unique_org_feature_flag'),
        ),
        migrations.AddConstraint(
            model_name='organizationaddon',
            constraint=models.UniqueConstraint(fields=('organization', 'addon_key'), name='unique_org_addon'),
        ),
    ]
