# Generated by Django 5.2.17 on 2026-09-06 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_featureflag_organization_and_more'),
        ('workspaces', '0004_membership_permissions_workspace_soft_budget_credits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Signed. Zero is legitimate: unlimited plans still record usage.')),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('OUTBOUND', 'Reply sent to an audience comment'), ('MONTHLY_RESET', 'Monthly allowance reset'), ('MANUAL_ADJUST', 'Manual adjustment')], max_length=16)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_ledger_entries', to='workspaces.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
            },
        ),
    ]
