# Generated by Django 5.2.17 on 2026-09-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_reply_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaddon',
            name='status',
            field=models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Trial expired')], default='TRIALING', max_length=16),
        ),
    ]
