# Generated by Django 5.2.17 on 2026-09-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_addon_expired_status'),
        ('workspaces', '0008_workspace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workspaces.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
