# Generated by Django 5.2.17 on 2026-09-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_subscription_item_and_organization'),
        ('workspaces', '0008_workspace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditledger',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='workspaces.organization'),
        ),
        migrations.AddField(
            model_name='videoledger',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='workspaces.organization'),
        ),
        migrations.AlterField(
            model_name='replyledger',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='workspaces.organization'),
        ),
    ]
