# Generated by Django 5.2.17 on 2026-09-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_ledger_organization_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('minor_units', models.PositiveSmallIntegerField(default=2)),
                ('symbol_first', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PackPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.IntegerField(default=0)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.currency')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.pack')),
            ],
            options={
                'ordering': ['pack', 'currency__code'],
                'constraints': [models.UniqueConstraint(fields=('pack', 'currency'), name='unique_pack_price_currency'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('pack',), name='one_default_price_per_pack')],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_cents', models.IntegerField(default=0)),
                ('annual_cents', models.IntegerField(default=0)),
                ('per_workspace_cents', models.IntegerField(default=0)),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=64)),
                ('stripe_price_id_annual', models.CharField(blank=True, max_length=64)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.currency')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.plan')),
            ],
            options={
                'ordering': ['plan', 'currency__code'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'currency'), name='unique_plan_price_currency'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('plan',), name='one_default_price_per_plan')],
            },
        ),
    ]
