# Generated by Django 5.2.17 on 2026-09-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_backfill_default_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_overage_item_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
