# Generated by Django 5.2.17 on 2026-09-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_subscription_overage_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_tracked_competitors',
            field=models.IntegerField(default=0),
        ),
    ]
