# Generated by Django 5.2.17 on 2026-10-04 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0017_workspace_market'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('domain', models.CharField(blank=True, max_length=253)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('APPLIED', 'Applied')], default='QUEUED', max_length=10)),
                ('stage', models.CharField(choices=[('RESOLVING', 'Resolving domain'), ('READING', 'Reading pages'), ('PRODUCTS', 'Finding products'), ('AUDIENCE', 'Reading audience signals'), ('COMPETITORS', 'Spotting competitors'), ('VOICE', 'Listening for voice'), ('PALETTE', 'Sampling palette and fonts'), ('DONE', 'Done')], default='RESOLVING', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('review', models.JSONField(blank=True, default=dict)),
                ('edits', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_imports', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BrandCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('sections', models.JSONField(default=dict)),
                ('identity', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_cores', to='workspaces.workspace')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cores', to='brand.brandimport')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'version'), name='unique_brand_core_version')],
            },
        ),
    ]
