# Generated by Django 5.2.17 on 2026-10-04 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('workspaces', '0017_workspace_market'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('domain', models.CharField(blank=True, max_length=253)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('APPLIED', 'Applied')], default='QUEUED', max_length=10)),
                ('stage', models.CharField(choices=[('OPENING', 'Opening the page'), ('DETAILS', 'Title, price and SKU'), ('PHOTOS', 'Collecting photos'), ('DESCRIPTION', 'Description and features'), ('CLAIMS', 'Spotting claims'), ('DONE', 'Done')], default='OPENING', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_imports', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
