# Generated by Django 5.2.17 on 2026-08-12 23:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('content', '0004_post_status_scheduled_at_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepurposeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile_threshold', models.FloatField(default=80.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'repurpose configuration',
                'verbose_name_plural': 'repurpose configuration',
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='channels.socialaccount')),
            ],
            options={
                'ordering': ['-captured_at'],
                'constraints': [models.UniqueConstraint(fields=('social_account', 'captured_at'), name='unique_snapshot_per_capture')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('sentiment', models.CharField(choices=[('POS', 'Positive'), ('NEU', 'Neutral'), ('NEG', 'Negative')], default='NEU', max_length=3)),
                ('sentiment_score', models.FloatField(default=0)),
                ('posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='content.posttarget')),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['post_target', 'sentiment'], name='analytics_c_post_ta_7325ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('post_target', 'external_id'), name='unique_comment_per_target')],
            },
        ),
        migrations.CreateModel(
            name='PostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='content.posttarget')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['post_target', '-captured_at'], name='analytics_p_post_ta_87f5cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('post_target', 'captured_at'), name='unique_metric_per_capture')],
            },
        ),
        migrations.CreateModel(
            name='RepurposeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile', models.FloatField(default=0)),
                ('reason', models.CharField(choices=[('EVERGREEN', 'Kept earning'), ('SPIKE_STEADY', 'Spiked, then held')], default='EVERGREEN', max_length=16)),
                ('score', models.FloatField(default=0)),
                ('surfaced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repurpose_candidates', to='content.post')),
                ('reissued_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repurposed_from', to='content.post')),
            ],
            options={
                'ordering': ['-score', '-surfaced_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dismissed_at__isnull', True), ('reissued_post__isnull', True)), fields=('post',), name='unique_open_repurpose_candidate_per_post')],
            },
        ),
    ]
