# Generated by Django 5.2.17 on 2026-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repurposecandidate',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
