# Generated by Django 5.2.17 on 2026-09-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_repurposecandidate_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=32)),
                ('metric_key', models.CharField(max_length=64)),
                ('available', models.BooleanField(default=True)),
                ('latency_hint', models.DurationField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'metric capabilities',
                'ordering': ['provider_key', 'platform', 'metric_key'],
                'constraints': [models.UniqueConstraint(fields=('provider_key', 'platform', 'metric_key'), name='unique_provider_platform_metric')],
            },
        ),
    ]
