# Generated by Django 5.2.17 on 2026-09-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_metriccapability'),
        ('content', '0004_post_status_scheduled_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetric',
            name='availability',
            field=models.CharField(choices=[('MEASURED', 'Measured'), ('UNAVAILABLE', 'Provider cannot report this'), ('PENDING', 'Provider sync still in flight')], default='MEASURED', max_length=12),
        ),
        migrations.AddField(
            model_name='postmetric',
            name='provider_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='postmetric',
            name='raw_payload',
            field=models.BinaryField(blank=True, default=bytes),
        ),
        migrations.AddField(
            model_name='postmetric',
            name='reactions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmetric',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmetric',
            name='source',
            field=models.CharField(choices=[('PROVIDER', 'A measurement provider'), ('FAKE', 'The test fake — never insight')], default='PROVIDER', max_length=8),
        ),
        migrations.AlterField(
            model_name='accountsnapshot',
            name='followers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountsnapshot',
            name='following',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountsnapshot',
            name='total_posts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmetric',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmetric',
            name='comments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmetric',
            name='engagement_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmetric',
            name='impressions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmetric',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmetric',
            name='saves',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmetric',
            name='shares',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        # --- the Comment -> AudienceComment rename (P0-02) ------------------
        #
        # Hand-written. `makemigrations` proposed CreateModel + DeleteModel,
        # which would have dropped every audience comment ever ingested and
        # rebuilt an empty table. The model was promoted to first class; the
        # rows did not change and neither does the physical table, which stays
        # `analytics_comment` via `Meta.db_table` so this is a state-only
        # rename with no data movement at all.
        migrations.RenameModel(old_name='Comment', new_name='AudienceComment'),
        migrations.AlterModelTable(name='audiencecomment', table='analytics_comment'),
        migrations.AddField(
            model_name='audiencecomment',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='audiencecomment',
            name='availability',
            field=models.CharField(
                choices=[
                    ('MEASURED', 'Measured'),
                    ('UNAVAILABLE', 'Provider cannot report this'),
                    ('PENDING', 'Provider sync still in flight'),
                ],
                default='MEASURED',
                max_length=12,
            ),
        ),
    ]
