# Generated by Django 5.2.17 on 2026-09-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_metrics_provenance_and_audience_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(max_length=32, unique=True)),
                ('cursor', models.CharField(blank=True, max_length=512)),
                ('bootstrapped_at', models.DateTimeField(blank=True, null=True)),
                ('empty_reads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
