# Generated by Django 5.2.17 on 2026-09-06 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_provider_cursor'),
        ('content', '0004_post_status_scheduled_at_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureDeferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rung', models.DateTimeField()),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_deferrals', to='content.posttarget')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post_target', 'rung'), name='unique_deferral_per_rung')],
            },
        ),
    ]
