# Generated by Django 5.2.17 on 2026-09-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_capture_deferral'),
        ('content', '0004_post_status_scheduled_at_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceCaptureState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_captured_at', models.DateTimeField(blank=True, null=True)),
                ('unavailable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience_state', to='content.posttarget')),
            ],
        ),
    ]
