# Generated by Django 5.2.17 on 2026-09-12 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_report_reportrun_reportsharelink_and_more'),
        ('channels', '0002_alter_socialaccount_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('dimension', models.CharField(choices=[('AGE', 'Age'), ('GENDER', 'Gender'), ('COUNTRY', 'Country'), ('CITY', 'City'), ('LANGUAGE', 'Language')], max_length=16)),
                ('breakdown', models.JSONField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('MEASURED', 'Measured'), ('UNAVAILABLE', 'Provider cannot report this'), ('PENDING', 'Provider sync still in flight')], default='MEASURED', max_length=12)),
                ('provider_key', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='channels.socialaccount')),
            ],
            options={
                'ordering': ['-captured_at'],
                'constraints': [models.UniqueConstraint(fields=('social_account', 'dimension', 'captured_at'), name='one_demographic_per_account_dimension_capture')],
            },
        ),
    ]
