# Generated by Django 5.2.17 on 2026-09-12 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_generation_source_media_alter_generation_mode_and_more'),
        ('content', '0014_new_platforms'),
        ('planning', '0003_bulkoperation_bulkoperationitem'),
        ('products', '0002_autopilotconfig_autopilotdraft_autopilotjob'),
        ('workspaces', '0016_approval_action_required_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTasteOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_override', to='products.product')),
                ('references', models.ManyToManyField(blank=True, related_name='product_taste_references', to='content.post')),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STRUCTURE', 'Structure'), ('TIMING', 'Timing'), ('TOPIC', 'Topic'), ('FORMAT', 'Format'), ('VOICE', 'Voice')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_rules', to=settings.AUTH_USER_MODEL)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='taste.ruleset')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('hard_constraints', models.JSONField(blank=True, default=dict)),
                ('voice', models.JSONField(blank=True, default=dict)),
                ('structural', models.JSONField(blank=True, default=dict)),
                ('topic_posture', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taste_profiles', to=settings.AUTH_USER_MODEL)),
                ('reference_examples', models.ManyToManyField(blank=True, related_name='taste_references', to='content.post')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profiles', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ContentCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('generated', 'Generated'), ('screened_out', 'Screened out'), ('pending_review', 'Pending review'), ('rejected', 'Rejected'), ('regenerating', 'Regenerating'), ('expired', 'Expired'), ('approved', 'Approved')], default='generated', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parent_reason_code', models.CharField(blank=True, max_length=32)),
                ('screened_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='planning.campaign')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='ai.generation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='taste.contentcandidate')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_candidates', to='content.post')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='products.product')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='workspaces.workspace')),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='taste.ruleset')),
                ('taste_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='taste.tasteprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_as_shown', models.JSONField(blank=True, default=dict)),
                ('taste_profile_version', models.PositiveIntegerField()),
                ('ruleset_version', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt_context', models.JSONField(blank=True, default=dict)),
                ('model_identity', models.CharField(blank=True, max_length=120)),
                ('prompt_template_version', models.CharField(blank=True, max_length=40)),
                ('verdict', models.CharField(choices=[('accepted', 'Accepted'), ('accepted_with_edits', 'Accepted with edits'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=24)),
                ('reason_code', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
                ('edit_diff', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='taste.contentcandidate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['candidate', '-created_at'], name='taste_decis_candida_04b14e_idx'), models.Index(fields=['verdict', 'reason_code'], name='taste_decis_verdict_3cc3eb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('workspace', 'version'), name='ruleset_version_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace',), name='one_active_ruleset_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='tasteprofile',
            constraint=models.UniqueConstraint(fields=('workspace', 'version'), name='taste_profile_version_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='tasteprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace',), name='one_active_taste_profile_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='contentcandidate',
            index=models.Index(fields=['workspace', 'state', '-created_at'], name='taste_conte_workspa_b31109_idx'),
        ),
    ]
