# Generated by Django 5.2.17 on 2026-09-14 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
        ('taste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='taste.rule'),
        ),
        migrations.AddField(
            model_name='rule',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_rules', to='learn.finding'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='taste.contentcandidate'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='taste_profile_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['rule', '-created_at'], name='taste_decis_rule_id_4c6ee4_idx'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('candidate__isnull', False), ('rule__isnull', True)), models.Q(('candidate__isnull', True), ('rule__isnull', False)), _connector='OR'), name='decision_is_about_exactly_one_subject'),
        ),
    ]
