# Generated by Django 5.2.17 on 2026-09-14 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
        ('taste', '0002_decision_rule_rule_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_rulesets', to='learn.digest'),
        ),
    ]
