# Generated by Django 5.2.17 on 2026-09-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateBudgetWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('connection', models.CharField(max_length=128)),
                ('window_start', models.DateTimeField()),
                ('consumed_publish', models.PositiveIntegerField(default=0)),
                ('consumed_ingest', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['window_start'], name='common_rate_window__f0fd2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'connection', 'window_start'), name='unique_rate_budget_window')],
            },
        ),
    ]
