# Generated by Django 5.2.17 on 2026-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_rate_budget_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=120)),
                ('migration', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('rows_touched', models.PositiveIntegerField(default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
