# Generated by Django 5.2.17 on 2026-08-09 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_mediaasset_generation_post_generation_post_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=8)),
                ('send_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_to', models.DateTimeField(blank=True, null=True)),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('state', models.CharField(choices=[('ARMED', 'Armed'), ('SENT', 'Sent'), ('CONFIRMED', 'Confirmed'), ('SNOOZED', 'Snoozed'), ('SKIPPED', 'Skipped'), ('EXPIRED', 'Expired')], default='ARMED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='content.post')),
            ],
            options={
                'ordering': ['send_at'],
                'indexes': [models.Index(fields=['state', 'send_at'], name='reminders_r_state_156a92_idx'), models.Index(fields=['post', '-created_at'], name='reminders_r_post_id_1f8731_idx')],
            },
        ),
    ]
