# Generated by Django 5.2.17 on 2026-09-11 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0012_post_content_kind'),
        ('workspaces', '0015_approvalaction_guest_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('THEME', 'Ongoing theme'), ('SPRINT', 'Planning sprint')], default='THEME', max_length=8)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='PLANNING', max_length=10)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('planned_volume', models.JSONField(blank=True, default=dict)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefed_campaigns', to='content.post')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_additions', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.campaign')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_items', to='content.post')),
            ],
            options={
                'ordering': ['-added_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['workspace', 'status'], name='planning_ca_workspa_26e56c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['workspace', 'starts_at', 'ends_at'], name='planning_ca_workspa_f75988_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='campaign_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='campaignitem',
            constraint=models.UniqueConstraint(fields=('campaign', 'post'), name='campaign_item_is_unique'),
        ),
    ]
