# Generated by Django 5.2.17 on 2026-09-14 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
        ('planning', '0003_bulkoperation_bulkoperationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='digest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_of_record', to='learn.digest'),
        ),
    ]
