# Generated by Django 5.2.17 on 2026-08-12 21:44

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        # `deploy/postgres/init/01-extensions.sql` creates this for the dev
        # database, but an init script only runs for the container's *first*
        # database — a test database, a CI database and a restored production
        # database all miss it. The app that needs the extension owns creating
        # it, so `migrate` alone is enough to stand the schema up anywhere.
        VectorExtension(),
        migrations.CreateModel(
            name='TrendCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('facebook', 'Facebook')], max_length=32)),
                ('label', models.CharField(max_length=200)),
                ('centroid', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('velocity_score', models.FloatField(default=0)),
                ('recency_score', models.FloatField(default=0)),
                ('composite_score', models.FloatField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_clusters', to='categories.category')),
            ],
            options={
                'ordering': ['-composite_score'],
            },
        ),
        migrations.CreateModel(
            name='TrendSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('facebook', 'Facebook')], max_length=32)),
                ('kind', models.CharField(choices=[('ADLIB', 'Meta Ad Library'), ('CREATIVE_CENTER', 'TikTok Creative Center'), ('YOUTUBE', 'YouTube'), ('REDDIT', 'Reddit'), ('RSS', 'RSS feed'), ('ACCOUNT', 'Tracked account')], max_length=24)),
                ('vendor', models.CharField(blank=True, max_length=60)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('watermark_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_sources', to='categories.category')),
            ],
            options={
                'ordering': ['category__name', 'platform', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='TrendItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('modality', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='TEXT', max_length=8)),
                ('author_handle', models.CharField(blank=True, max_length=200)),
                ('author_followers', models.PositiveIntegerField(default=0)),
                ('body', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('posted_at', models.DateTimeField()),
                ('raw_metrics', models.JSONField(blank=True, default=dict)),
                ('lang', models.CharField(blank=True, max_length=8)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('excluded_reason', models.CharField(blank=True, max_length=32)),
                ('engagement_score', models.FloatField(default=0)),
                ('velocity_score', models.FloatField(default=0)),
                ('recency_score', models.FloatField(default=0)),
                ('authority_score', models.FloatField(default=0)),
                ('composite_score', models.FloatField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='trends.trendcluster')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trends.trendsource')),
            ],
            options={
                'ordering': ['-composite_score', '-posted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trendcluster',
            index=models.Index(fields=['category', 'platform', '-composite_score'], name='trends_tren_categor_9d5e17_idx'),
        ),
        migrations.AddIndex(
            model_name='trendcluster',
            index=models.Index(fields=['expires_at'], name='trends_tren_expires_b60b9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='trendsource',
            constraint=models.UniqueConstraint(fields=('category', 'platform', 'kind', 'vendor'), name='unique_trend_source_per_category_platform_kind_vendor'),
        ),
        migrations.AddIndex(
            model_name='trenditem',
            index=models.Index(fields=['source', '-posted_at'], name='trends_tren_source__2de8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='trenditem',
            index=models.Index(fields=['cluster', '-composite_score'], name='trends_tren_cluster_45d7d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='trenditem',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_trend_item_per_source'),
        ),
    ]
