# Generated by Django 5.2.17 on 2026-09-12 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('trends', '0002_alter_trendcluster_platform_and_more'),
        ('workspaces', '0016_approval_action_required_permission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trendsource',
            name='unique_trend_source_per_category_platform_kind_vendor',
        ),
        migrations.AddField(
            model_name='trendsource',
            name='handle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trendsource',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='trendsource',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_sources', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='trendsource',
            name='kind',
            field=models.CharField(choices=[('ADLIB', 'Meta Ad Library'), ('CREATIVE_CENTER', 'TikTok Creative Center'), ('YOUTUBE', 'YouTube'), ('REDDIT', 'Reddit'), ('RSS', 'RSS feed'), ('ACCOUNT', 'Tracked account'), ('COMPETITOR', 'Competitor account')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='trendsource',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('category', 'platform', 'kind', 'vendor'), name='unique_shared_trend_source'),
        ),
        migrations.AddConstraint(
            model_name='trendsource',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'platform', 'kind', 'handle'), name='unique_tracked_source_per_workspace'),
        ),
    ]
