# Generated by Django 5.2.17 on 2026-10-09 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0016_post_cancelled_status'),
        ('workspaces', '0017_workspace_market'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(blank=True, null=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('RUNNING', 'Running'), ('DONE', 'Done')], default='RUNNING', max_length=8)),
                ('verdict', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FIX', 'Fix required'), ('BLOCK', 'Block')], max_length=8)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='content.post')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['post', '-created_at'], name='checks_chec_post_id_9825ba_idx')],
            },
        ),
    ]
