# Generated by Django 5.2.17 on 2026-09-14 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0003_bulkoperation_bulkoperationitem'),
        ('workspaces', '0016_approval_action_required_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('narration', models.TextField(blank=True)),
                ('narration_source', models.CharField(choices=[('MODEL', 'Model narration'), ('TEMPLATE', 'Template fallback')], default='TEMPLATE', max_length=10)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('taste_profile_version', models.PositiveIntegerField(blank=True, null=True)),
                ('ruleset_version', models.PositiveIntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='planning.campaign')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_digests', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.JSONField(blank=True, default=dict)),
                ('comparison', models.JSONField(blank=True, default=dict)),
                ('confidence', models.CharField(choices=[('STRONG', 'Strong'), ('EMERGING', 'Emerging'), ('INSUFFICIENT', 'Insufficient')], max_length=12)),
                ('sample_size', models.PositiveIntegerField()),
                ('baseline_size', models.PositiveIntegerField(default=0)),
                ('campaigns_observed', models.PositiveIntegerField(default=1)),
                ('excluded_reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='learn.digest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['workspace', '-generated_at'], name='learn_diges_workspa_bfec64_idx'),
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['campaign', '-generated_at'], name='learn_diges_campaig_bcf7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['digest', 'confidence'], name='learn_findi_digest__7bfe66_idx'),
        ),
    ]
