# Generated by Django 5.2.17 on 2026-09-07 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0010_post_visibility'),
        ('workspaces', '0011_contract_workspace_commercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LATER', 'Later'), ('DONE', 'Done')], default='OPEN', max_length=8)),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Team only'), ('SHARED', 'Shared with clients')], default='INTERNAL', max_length=8)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_threads', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_threads', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='content.post')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_threads', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Team only'), ('SHARED', 'Shared with clients')], default='INTERNAL', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaboration.comment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='collaboration.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_start', models.PositiveIntegerField()),
                ('anchor_end', models.PositiveIntegerField()),
                ('anchor_text', models.TextField()),
                ('anchor_hash', models.CharField(max_length=64)),
                ('orphaned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='collaboration.comment')),
            ],
            options={
                'ordering': ['anchor_start', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('anchor_end__gt', models.F('anchor_start'))), name='annotation_range_is_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='collaboration.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('comment', 'user', 'emoji'), name='unique_reaction_per_user_comment_emoji')],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['post', '-created_at'], name='collaborati_post_id_e0361c_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['workspace', 'status'], name='collaborati_workspa_a68905_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['thread', 'created_at'], name='collaborati_thread__638789_idx'),
        ),
    ]
