# Generated by Django 5.2.17 on 2026-08-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspace_provider_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('facebook', 'Facebook')], max_length=16)),
                ('handle', models.CharField(blank=True, max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('provider_account_id', models.CharField(max_length=128)),
                ('followers_cached', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REAUTH_REQUIRED', 'Reauth required'), ('OVER_LIMIT', 'Over plan limit'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['platform', 'handle'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='channels_so_workspa_8b7e1b_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'platform', 'provider_account_id'), name='unique_workspace_platform_provider_account')],
            },
        ),
    ]
