# Generated by Django 5.2.17 on 2026-08-09 08:38

import content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=8)),
                ('file', models.FileField(max_length=255, upload_to=content.models.media_asset_upload_to)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, help_text='sha256 hex digest.', max_length=64)),
                ('source', models.CharField(choices=[('UPLOAD', 'Upload'), ('GENERATED', 'Generated')], default='UPLOAD', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('CHANGES_REQUESTED', 'Changes requested'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('REMINDER_ARMED', 'Reminder armed'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], default='DRAFT', max_length=20)),
                ('delivery_mode', models.CharField(blank=True, choices=[('REMINDER', 'Reminder'), ('AUTO_PUBLISH', 'Auto-publish')], max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('AI', 'AI'), ('AUTOPILOT', 'Autopilot'), ('REPURPOSE', 'Repurpose')], default='MANUAL', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='categories.category')),
                ('origin_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repurposed_posts', to='content.post')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_attachments', to='content.mediaasset')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='content.post')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='media_assets',
            field=models.ManyToManyField(blank=True, related_name='posts', through='content.PostMediaAttachment', to='content.mediaasset'),
        ),
        migrations.CreateModel(
            name='PostTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('facebook', 'Facebook')], max_length=16)),
                ('rendered_payload', models.JSONField(blank=True, default=dict)),
                ('provider_post_id', models.CharField(blank=True, max_length=128)),
                ('platform_post_id', models.CharField(blank=True, max_length=128)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('error_detail', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='content.post')),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['workspace', '-created_at'], name='content_med_workspa_14b969_idx'),
        ),
        migrations.AddConstraint(
            model_name='postmediaattachment',
            constraint=models.UniqueConstraint(fields=('post', 'media_asset'), name='unique_post_media_asset'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['workspace', '-created_at'], name='content_pos_workspa_575b66_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['workspace', 'status'], name='content_pos_workspa_bfb756_idx'),
        ),
        migrations.AddIndex(
            model_name='posttarget',
            index=models.Index(fields=['state'], name='content_pos_state_7cf8b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='posttarget',
            constraint=models.UniqueConstraint(fields=('post', 'platform'), name='unique_post_platform_target'),
        ),
    ]
