# Generated by Django 5.2.17 on 2026-08-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('content', '0002_mediaasset_generation_post_generation_post_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posttarget',
            name='unique_post_platform_target',
        ),
        migrations.AddField(
            model_name='posttarget',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_targets', to='channels.socialaccount'),
        ),
        migrations.AddConstraint(
            model_name='posttarget',
            constraint=models.UniqueConstraint(fields=('post', 'social_account'), name='unique_post_social_account_target'),
        ),
        migrations.AddConstraint(
            model_name='posttarget',
            constraint=models.UniqueConstraint(condition=models.Q(('social_account__isnull', True)), fields=('post', 'platform'), name='unique_post_platform_target_unconnected'),
        ),
    ]
