# Generated by Django 5.2.17 on 2026-08-12 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('categories', '0001_initial'),
        ('content', '0003_remove_posttarget_unique_post_platform_target_and_more'),
        ('products', '0001_initial'),
        ('workspaces', '0002_workspace_provider_profile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'scheduled_at'], name='content_pos_status_51b379_idx'),
        ),
    ]
