# Generated by Django 5.2.17 on 2026-09-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_status_scheduled_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttarget',
            name='body_override',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posttarget',
            name='media_override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posttarget',
            name='options_schema_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posttarget',
            name='platform_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
