# Generated by Django 5.2.17 on 2026-09-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_post_target_overrides'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postmediaattachment',
            name='unique_post_media_asset',
        ),
        migrations.AddField(
            model_name='postmediaattachment',
            name='alt_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='postmediaattachment',
            name='target_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_alt_overrides', to='content.posttarget'),
        ),
        migrations.AddConstraint(
            model_name='postmediaattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('target_override__isnull', True)), fields=('post', 'media_asset'), name='unique_post_media_asset'),
        ),
        migrations.AddConstraint(
            model_name='postmediaattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('target_override__isnull', False)), fields=('post', 'media_asset', 'target_override'), name='unique_post_media_asset_target_override'),
        ),
    ]
