# Generated by Django 5.2.17 on 2026-09-07 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_postmediaattachment_unique_post_media_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('is_checkpoint', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_revisions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.post')),
            ],
            options={
                'ordering': ['-sequence'],
                'indexes': [models.Index(fields=['created_at'], name='content_pos_created_4d9303_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'sequence'), name='unique_post_revision_seq')],
            },
        ),
    ]
