# Generated by Django 5.2.17 on 2026-09-07 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_postrevision'),
        ('workspaces', '0011_contract_workspace_commercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('content_kind', models.CharField(choices=[('SOCIAL', 'Social'), ('DOC', 'Document')], default='SOCIAL', max_length=8)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_templates', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrule', models.TextField(help_text='RFC 5545 RRULE, without the DTSTART line.')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('horizon_days', models.PositiveSmallIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='content.posttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_occurrences', to='content.post')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='content.recurrencerule')),
            ],
            options={
                'ordering': ['slot_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='posttemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_post_template_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='recurrencerule',
            index=models.Index(fields=['active'], name='content_rec_active_412369_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurrenceoccurrence',
            constraint=models.UniqueConstraint(fields=('rule', 'slot_at'), name='unique_recurrence_slot'),
        ),
    ]
