# Generated by Django 5.2.17 on 2026-09-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_posttemplate_recurrencerule_recurrenceoccurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='content.mediaasset'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='source',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('GENERATED', 'Generated'), ('DERIVED', 'Derived')], default='UPLOAD', max_length=16),
        ),
    ]
