# Generated by Django 5.2.17 on 2026-09-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_mediaasset_derived_from_alter_mediaasset_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('INTERNAL', 'Team only'), ('SHARED', 'Shared with clients')], default='INTERNAL', max_length=8),
        ),
    ]
