# Generated by Django 5.2.17 on 2026-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_post_approval_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_kind',
            field=models.CharField(choices=[('SOCIAL', 'Social post'), ('DOC', 'Document')], default='SOCIAL', max_length=8),
        ),
        migrations.AddField(
            model_name='post',
            name='doc_body',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='posttemplate',
            name='content_kind',
            field=models.CharField(choices=[('SOCIAL', 'Social post'), ('DOC', 'Document')], default='SOCIAL', max_length=8),
        ),
    ]
