# Generated by Django 5.2.17 on 2026-09-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_post_content_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttarget',
            name='post_format',
            field=models.CharField(choices=[('FEED', 'Feed post'), ('STORY', 'Story'), ('REEL', 'Reel'), ('SHORT', 'Short'), ('CAROUSEL', 'Carousel'), ('PDF_CAROUSEL', 'Document carousel')], default='FEED', max_length=16),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=8),
        ),
    ]
