# Generated by Django 5.2.17 on 2026-09-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_post_target_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttarget',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('facebook', 'Facebook'), ('x', 'X'), ('pinterest', 'Pinterest'), ('google_business', 'Google Business Profile')], max_length=16),
        ),
    ]
