# Generated by Django 5.2.17 on 2026-10-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_new_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='planned_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AI', 'AI'), ('AUTOPILOT', 'Autopilot'), ('REPURPOSE', 'Repurpose'), ('UPLOAD', 'Uploaded')], default='MANUAL', max_length=16),
        ),
    ]
