# Generated by Django 5.2.17 on 2026-10-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_post_planned_platforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_REVIEW", "Pending review"),
                    ("CHANGES_REQUESTED", "Changes requested"),
                    ("REJECTED", "Rejected"),
                    ("APPROVED", "Approved"),
                    ("SCHEDULED", "Scheduled"),
                    ("REMINDER_ARMED", "Reminder armed"),
                    ("PUBLISHING", "Publishing"),
                    ("PUBLISHED", "Published"),
                    ("FAILED", "Failed"),
                    ("PAUSED", "Paused"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
