# Generated by Django 5.2.17 on 2026-08-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('content', '0001_initial'),
        ('products', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityGateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_similarity_threshold', models.FloatField(default=0.6)),
                ('max_regeneration_attempts', models.PositiveSmallIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=8)),
                ('mode', models.CharField(choices=[('IDEA', 'Idea'), ('TREND', 'Trend'), ('REPURPOSE', 'Repurpose'), ('REWRITE', 'Rewrite'), ('PRODUCT', 'Product'), ('AUTOPILOT', 'Autopilot'), ('RECIPE', 'Recipe'), ('REVISION', 'Revision')], max_length=16)),
                ('prompt', models.TextField(blank=True)),
                ('output_type', models.CharField(blank=True, max_length=32)),
                ('aspect', models.CharField(blank=True, default='1:1', max_length=16)),
                ('render_style', models.CharField(blank=True, max_length=64)),
                ('scene', models.CharField(blank=True, max_length=200)),
                ('motion', models.CharField(blank=True, max_length=64)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('is_batch', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('credits_charged', models.PositiveIntegerField(default=0)),
                ('video_units_charged', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('error_detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='categories.category')),
                ('parent_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='ai.generation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=8)),
                ('mode', models.CharField(blank=True, choices=[('IDEA', 'Idea'), ('TREND', 'Trend'), ('REPURPOSE', 'Repurpose'), ('REWRITE', 'Rewrite'), ('PRODUCT', 'Product'), ('AUTOPILOT', 'Autopilot'), ('RECIPE', 'Recipe'), ('REVISION', 'Revision')], max_length=16)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('credits', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'mode', 'provider', 'model'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'mode', 'provider', 'model'), name='unique_generation_cost_row')],
            },
        ),
        migrations.CreateModel(
            name='GenerationVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=8)),
                ('body', models.TextField(blank=True)),
                ('platform', models.CharField(blank=True, max_length=16)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('rationale', models.CharField(blank=True, max_length=300)),
                ('was_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ai.generation')),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_variants', to='content.mediaasset')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('identity_score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField()),
                ('attempt', models.PositiveSmallIntegerField()),
                ('rejected_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='ai.generation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='ai.generationvariant')),
            ],
            options={
                'ordering': ['generation', 'attempt'],
            },
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tone_descriptors', models.JSONField(blank=True, default=list)),
                ('banned_phrases', models.JSONField(blank=True, default=list)),
                ('exemplar_post_ids', models.JSONField(blank=True, default=list)),
                ('system_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='voice_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='ai.voiceprofile'),
        ),
        migrations.AddIndex(
            model_name='generationvariant',
            index=models.Index(fields=['generation', 'rank'], name='ai_generati_generat_ac5095_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['generation', 'attempt'], name='ai_qualityc_generat_a2f876_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['workspace', '-created_at'], name='ai_generati_workspa_5d118b_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['workspace', 'status'], name='ai_generati_workspa_93b118_idx'),
        ),
    ]
