# Generated by Django 5.2.17 on 2026-09-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('content', '0009_mediaasset_derived_from_alter_mediaasset_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='source_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captions', to='content.mediaasset'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='mode',
            field=models.CharField(choices=[('IDEA', 'Idea'), ('TREND', 'Trend'), ('REPURPOSE', 'Repurpose'), ('REWRITE', 'Rewrite'), ('PRODUCT', 'Product'), ('AUTOPILOT', 'Autopilot'), ('RECIPE', 'Recipe'), ('REVISION', 'Revision'), ('CAPTION', 'Caption'), ('SUGGEST', 'Suggest')], max_length=16),
        ),
        migrations.AlterField(
            model_name='generationcost',
            name='mode',
            field=models.CharField(blank=True, choices=[('IDEA', 'Idea'), ('TREND', 'Trend'), ('REPURPOSE', 'Repurpose'), ('REWRITE', 'Rewrite'), ('PRODUCT', 'Product'), ('AUTOPILOT', 'Autopilot'), ('RECIPE', 'Recipe'), ('REVISION', 'Revision'), ('CAPTION', 'Caption'), ('SUGGEST', 'Suggest')], max_length=16),
        ),
    ]
