# Generated by Django 5.2.17 on 2026-09-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_generation_source_media_alter_generation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='prompt_template_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='generation',
            name='ruleset_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='taste_profile_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
