# Generated by Django 5.2.17 on 2026-09-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_generation_prompt_template_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='paid_slots',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='generationcost',
            name='unlock_percent',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='generationcost',
            name='variant_pool',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='generationvariant',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationvariant',
            name='unlock_charged',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
