# Generated by Django 5.2.17 on 2026-09-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_generation_paid_slots_generationcost_unlock_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='variant_pool',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
