# Generated by Django 5.2.17 on 2026-10-02 22:06

import ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_generation_variant_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='creative',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generationvariant',
            name='hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generationvariant',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='generationvariant',
            name='identity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CreativeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('scene', 'Scene'), ('light', 'Light'), ('camera', 'Camera angle'), ('cast', 'Who is in the frame'), ('vibe', 'Cast vibe'), ('mood', 'Mood'), ('palette', 'Palette'), ('language', 'Content language'), ('cta', 'Call to action'), ('format', 'Format'), ('tempo', 'Tempo (creativity)'), ('dynamics', 'Dynamics (colour intensity)'), ('tone', 'Voice'), ('toggle', 'On/off option'), ('preset', 'Preset'), ('quick_tag', 'Brief quick tag')], max_length=16)),
                ('key', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('icon_paths', models.JSONField(blank=True, default=list, validators=[ai.models._validate_icon_paths])),
                ('colors', models.JSONField(blank=True, default=list, validators=[ai.models._validate_colors])),
                ('prompt_fragment', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['kind', 'is_active'], name='ai_creative_kind_eb6ff5_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'key'), name='unique_creative_option_key')],
            },
        ),
    ]
