# Generated by Django 5.2.17 on 2026-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_creative_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeoption',
            name='kind',
            field=models.CharField(choices=[('scene', 'Scene'), ('light', 'Light'), ('camera', 'Camera angle'), ('cast', 'Who is in the frame'), ('vibe', 'Cast vibe'), ('mood', 'Mood'), ('palette', 'Palette'), ('language', 'Content language'), ('cta', 'Call to action'), ('format', 'Format'), ('tempo', 'Tempo (creativity)'), ('dynamics', 'Dynamics (colour intensity)'), ('tone', 'Voice'), ('toggle', 'On/off option'), ('preset', 'Preset'), ('quick_tag', 'Brief quick tag'), ('audience', 'Product audience'), ('tone_preset', 'Voice preset'), ('claim', 'Claim that needs proof'), ('shot_tag', 'Photo shot type'), ('aspect', 'Image aspect'), ('suggestion', 'Suggested entry')], max_length=16),
        ),
    ]
