# Generated by Django 5.2.17 on 2026-10-05 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_catalog_v2'),
        ('billing', '0018_seed_catalog'),
        ('content', '0016_post_cancelled_status'),
        ('products', '0004_product_brief'),
        ('workspaces', '0017_workspace_market'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeoption',
            name='kind',
            field=models.CharField(choices=[('scene', 'Scene'), ('light', 'Light'), ('camera', 'Camera angle'), ('cast', 'Who is in the frame'), ('vibe', 'Cast vibe'), ('mood', 'Mood'), ('palette', 'Palette'), ('language', 'Content language'), ('cta', 'Call to action'), ('format', 'Format'), ('tempo', 'Tempo (creativity)'), ('dynamics', 'Dynamics (colour intensity)'), ('tone', 'Voice'), ('toggle', 'On/off option'), ('preset', 'Preset'), ('quick_tag', 'Brief quick tag'), ('audience', 'Product audience'), ('tone_preset', 'Voice preset'), ('claim', 'Claim that needs proof'), ('shot_tag', 'Photo shot type'), ('aspect', 'Image aspect'), ('suggestion', 'Suggested entry'), ('revise_reason', 'Why regenerate'), ('video_length', 'Video length'), ('motion', 'Camera motion'), ('video_aspect', 'Video frame'), ('reel_style', 'Reel style'), ('music', 'Music bed'), ('video_extra', 'Video surcharge')], max_length=16),
        ),
        migrations.CreateModel(
            name='VideoRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('clip', 'Clip'), ('reel', 'Reel')], max_length=8)),
                ('spec', models.JSONField(default=dict)),
                ('text', models.TextField(blank=True)),
                ('estimate_id', models.CharField(max_length=32)),
                ('credits', models.PositiveIntegerField()),
                ('lines', models.JSONField(default=list)),
                ('render_s', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('phase', models.CharField(blank=True, max_length=24)),
                ('progress', models.FloatField(default=0)),
                ('review', models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('DISCARDED', 'Discarded'), ('HIDDEN', 'Hidden'), ('RETRIED', 'Retried as a new render')], max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_render', to='billing.creditledger')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_renders', to=settings.AUTH_USER_MODEL)),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_by', to='content.mediaasset')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_renders', to='content.post')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_renders', to='products.product')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='ai.videorender')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_renders', to='content.mediaasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_renders', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='ai_videoren_workspa_6f1c30_idx'), models.Index(fields=['workspace', 'status'], name='ai_videoren_workspa_facc93_idx')],
            },
        ),
    ]
