# Generated by Django 5.2.17 on 2026-09-06 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0008_workspace_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('headline', 'Headline'), ('bio', 'Bio'), ('hashtag', 'Hashtag'), ('hook', 'Hook'), ('thread-splitter', 'Thread splitter'), ('best-time', 'Best time to post')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('is_enabled', models.BooleanField(default=True)),
                ('credits_cost', models.PositiveIntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('headline', 'Headline'), ('bio', 'Bio'), ('hashtag', 'Hashtag'), ('hook', 'Hook'), ('thread-splitter', 'Thread splitter'), ('best-time', 'Best time to post')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('credits_charged', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_usages', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_usages', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='tools_toolu_workspa_773562_idx')],
            },
        ),
    ]
