# Generated by Django 5.2.17 on 2026-09-08 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0015_approvalaction_guest_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('post.submitted', 'A post was submitted for review'), ('post.approved', 'A post was approved'), ('post.changes_requested', 'Changes were requested'), ('post.rejected', 'A post was rejected'), ('thread.assigned', 'A thread was assigned to you'), ('thread.commented', 'Someone replied on a thread')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'workspace', '-created_at'], name='notificatio_user_id_46d464_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('post.submitted', 'A post was submitted for review'), ('post.approved', 'A post was approved'), ('post.changes_requested', 'Changes were requested'), ('post.rejected', 'A post was rejected'), ('thread.assigned', 'A thread was assigned to you'), ('thread.commented', 'Someone replied on a thread')], max_length=40)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['event_key'],
                'constraints': [models.UniqueConstraint(fields=('user', 'workspace', 'event_key'), name='unique_notification_preference')],
            },
        ),
    ]
