# Generated by Django 5.2.17 on 2026-08-09 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('content', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('restrictions', models.JSONField(blank=True, default=list)),
                ('adapter_ref', models.CharField(blank=True, max_length=128)),
                ('formats', models.JSONField(blank=True, default=list, help_text='ProductFormat values.')),
                ('platforms', models.JSONField(blank=True, default=list, help_text='content.Platform values.')),
                ('voice', models.CharField(blank=True, max_length=300)),
                ('moods', models.JSONField(blank=True, default=list)),
                ('hashtags_style', models.CharField(blank=True, choices=[('MINIMAL', 'Minimal'), ('MODERATE', 'Moderate'), ('HEAVY', 'Heavy')], max_length=16)),
                ('emoji_style', models.CharField(blank=True, choices=[('NONE', 'None'), ('LIGHT', 'Light'), ('EXPRESSIVE', 'Expressive')], max_length=16)),
                ('ctas', models.JSONField(blank=True, default=list)),
                ('completeness_score', models.PositiveSmallIntegerField(default=0)),
                ('is_generation_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
                ('reference_images', models.ManyToManyField(blank=True, related_name='products_referencing', to='content.mediaasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='products_pr_workspa_621398_idx'), models.Index(fields=['workspace', 'is_generation_ready'], name='products_pr_workspa_3d5481_idx')],
            },
        ),
    ]
