# Generated by Django 5.2.17 on 2026-08-13 21:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('content', '0004_post_status_scheduled_at_index'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutopilotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('cadence_days', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('lookahead_days', models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('strategy', models.CharField(choices=[('TREND_LED', 'Trend-led'), ('EVERGREEN', 'Evergreen'), ('PRODUCT_LED', 'Product-led'), ('PROMOTIONAL', 'Promotional')], default='PRODUCT_LED', max_length=16)),
                ('strategy_weights', models.JSONField(blank=True, default=dict)),
                ('latitude', models.PositiveSmallIntegerField(default=40, help_text="0 stays on the product's established pattern; 100 wanders furthest from it.", validators=[django.core.validators.MaxValueValidator(100)])),
                ('format_mix', models.JSONField(blank=True, default=dict)),
                ('platforms', models.JSONField(blank=True, default=list, help_text='content.Platform values.')),
                ('landing', models.CharField(choices=[('AUTO_CALENDAR', 'Straight to the calendar'), ('REVIEW_QUEUE', 'Review queue')], default='REVIEW_QUEUE', max_length=16)),
                ('auto_approve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autopilot', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='AutopilotDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=8)),
                ('platform', models.CharField(blank=True, max_length=16)),
                ('caption', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('strategy', models.CharField(choices=[('TREND_LED', 'Trend-led'), ('EVERGREEN', 'Evergreen'), ('PRODUCT_LED', 'Product-led'), ('PROMOTIONAL', 'Promotional')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autopilot_drafts', to='ai.generation')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_drafts', to='content.post')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopilot_drafts', to='products.product')),
            ],
            options={
                'ordering': ['scheduled_for', 'id'],
                'indexes': [models.Index(fields=['product', 'status'], name='products_au_product_80be26_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'scheduled_for'), name='unique_autopilot_slot_per_product')],
            },
        ),
        migrations.CreateModel(
            name='AutopilotJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('QUEUED', 'Queued for review'), ('BLOCKED_QUOTA', 'Blocked on quota'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='products.autopilotconfig')),
            ],
            options={
                'ordering': ['-run_at'],
                'indexes': [models.Index(fields=['config', '-run_at'], name='products_au_config__f7d75d_idx')],
            },
        ),
    ]
