# Generated by Django 5.2.17 on 2026-09-12 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_autopilotconfig_autopilotdraft_autopilotjob'),
        ('taste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilotdraft',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_drafts', to='taste.contentcandidate'),
        ),
    ]
