# Generated by Django 5.2.17 on 2026-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_autopilotdraft_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval_mode',
            field=models.CharField(blank=True, choices=[('me', 'Me'), ('manager', 'Brand manager'), ('two', 'Two-step')], max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='aspects',
            field=models.JSONField(blank=True, default=list, help_text='`aspect` option keys.'),
        ),
        migrations.AddField(
            model_name='product',
            name='audience',
            field=models.JSONField(blank=True, default=list, help_text='`audience` option keys.'),
        ),
        migrations.AddField(
            model_name='product',
            name='avoid_words',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='campaign_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='campaign_goal',
            field=models.CharField(blank=True, choices=[('awareness', 'Awareness'), ('traffic', 'Traffic'), ('sales', 'Sales')], max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='campaign_starts',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='caption_length',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('story', 'Story')], max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='claims',
            field=models.JSONField(blank=True, default=list, help_text='[{key, proof_media}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Caption languages, FR/EN (L-6).'),
        ),
        migrations.AddField(
            model_name='product',
            name='legal_mention',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lights',
            field=models.JSONField(blank=True, default=list, help_text='`light` option keys.'),
        ),
        migrations.AddField(
            model_name='product',
            name='mention_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='must_include',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='no_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='people',
            field=models.CharField(blank=True, help_text='A `cast` option key.', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_policy',
            field=models.JSONField(blank=True, default=dict, help_text='bg_remove / restage / unaltered / logo_legible.'),
        ),
        migrations.AddField(
            model_name='product',
            name='platform_plan',
            field=models.JSONField(blank=True, default=dict, help_text='{platform: {formats: [...], per_week: n}}'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.CharField(default='TND', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='ramadan_quiet_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='reference_tags',
            field=models.JSONField(blank=True, default=dict, help_text='{media id: shot_tag key} for reference_images.'),
        ),
        migrations.AddField(
            model_name='product',
            name='rules_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='scenes',
            field=models.JSONField(blank=True, default=list, help_text='`scene` option keys.'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='tone',
            field=models.JSONField(blank=True, default=dict, help_text='formal/bold/modern/poetic, 0-100.'),
        ),
        migrations.AddField(
            model_name='product',
            name='tone_preset',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='use_words',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashtags_style',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('MINIMAL', 'Minimal'), ('MODERATE', 'Moderate'), ('HEAVY', 'Heavy')], max_length=16),
        ),
    ]
